-- No-op migration.
--
-- This migration was generated out of order relative to
-- 20260305230000_specialty_models_and_clinic_template_assignment,
-- so applying it to a shadow database can fail with:
-- "no such table: ClinicSpecialty".
--
-- The actual specialty model creation and clinic template assignment logic
-- are handled by:
-- - 20260305230000_specialty_models_and_clinic_template_assignment
-- - 20260305234500_clinic_template_assignment
