import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static AppLocalizations of(BuildContext context) {
    final value = Localizations.of<AppLocalizations>(context, AppLocalizations);
    return value ?? AppLocalizations(const Locale('en'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'appName': 'Healthcare CRM',
      'designedForModernClinics': 'Designed for modern clinics',
      'skip': 'Skip',
      'next': 'Next',
      'getStarted': 'Get Started',
      'smartPatientManagement': 'Smart Patient Management',
      'smartPatientManagementBody': 'Track profiles, visits, and medical history with a clean mobile workflow.',
      'appointmentsThatFlow': 'Appointments That Flow',
      'appointmentsThatFlowBody': 'Organize daily schedules, reminders, and status updates in one dashboard.',
      'clinicAnalyticsInsights': 'Clinic Analytics Insights',
      'clinicAnalyticsInsightsBody': 'Monitor performance metrics and revenue trends for confident decisions.',
      'selectLanguageTitle': 'Choose your language',
      'selectLanguageSubtitle': 'Please select your preferred translation to continue.',
      'english': 'English',
      'arabic': 'Arabic',
      'continue': 'Continue',
      'dashboard': 'Dashboard',
      'failedToLoadDashboard': 'Failed to load dashboard metrics',
      'patients': 'Patients',
      'doctors': 'Doctors',
      'appointmentsToday': 'Appointments Today',
      'revenue': 'Revenue',
      'recentActivity': 'Recent Activity',
      'appointmentCompleted': 'Appointment marked as Completed',
      'newPatientAdded': 'A new patient profile was added',
      'prescriptions': 'Prescriptions',
      'appointments': 'Appointments',
      'unableToLoadAppointments': 'Unable to load appointments',
      'appointment': 'Appointment',
      'pending': 'pending',
      'noAppointments': 'No appointments',
      'noAppointmentsSubtitle': 'Create your first appointment and track statuses from one place.',
      'createAppointment': 'Create Appointment',
      'calendarView': 'Calendar view',
      'calendarViewSubtitle': 'Pick date and time from your integrated calendar',
      'appointmentStatus': 'Appointment status',
      'scheduled': 'Scheduled',
      'checkedIn': 'Checked In',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'saveAppointment': 'Save appointment',
      'unableToLoadDoctors': 'Unable to load doctors',
      'specialty': 'Specialty',
      'general': 'General',
      'scheduleReady': 'Schedule ready',
      'noDoctors': 'No doctors',
      'noDoctorsSubtitle': 'Add doctors, specialties, and schedule data to coordinate care.',
      'noPrescriptionsYet': 'No prescriptions yet',
      'noPrescriptionsSubtitle': 'Prescription API is not exposed yet; local workflow is enabled for UI readiness.',
      'medicine': 'Medicine',
      'dose': 'Dose',
      'na': 'N/A',
      'create': 'Create',
      'notifications': 'Notifications',
      'pushReadyReminder': 'Push-ready reminder event',
      'analytics': 'Analytics',
      'patientStatistics': 'Patient Statistics',
      'revenueTrend': 'Revenue Trend',
      'loginTitle': 'Clinic Login',
      'loginSubtitle': 'Secure access for doctors and staff',
      'welcomeBack': 'Welcome back',
      'email': 'Email',
      'password': 'Password',
      'login': 'Login',
      'signingIn': 'Signing in...',
      'forgotPassword': 'Forgot password?',
      'createClinicAccount': 'Create clinic account',
      'unlockWithBiometrics': 'Unlock with biometrics',
      'hipaaMinded': 'HIPAA-minded',
      'medicalFirstUx': 'Medical-first UX',
      'realtimeWorkflows': 'Realtime workflows',
      'createClinicAccountTitle': 'Create Clinic Account',
      'setupClinicWorkspace': 'Setup your clinic workspace',
      'setupClinicWorkspaceSubtitle': 'Create your premium healthcare experience in under 2 minutes.',
      'clinicName': 'Clinic name',
      'firstName': 'First name',
      'lastName': 'Last name',
      'adminEmail': 'Admin email',
      'creating': 'Creating...',
      'createPremiumWorkspace': 'Create premium workspace',
      'alreadyHaveAccount': 'Already have an account? Login',
      'forgotPasswordTitle': 'Forgot Password',
      'sendResetLink': 'Send reset link',
      'sending': 'Sending...',
      'resetInstructionsSent': 'If your account exists, reset instructions were sent.',
      'addPatient': 'Add patient',
      'patient': 'Patient',
      'noPatientsYet': 'No patients yet',
      'noPatientsSubtitle': 'Add your first patient to start tracking history and visits.',
      'home': 'Home',
      'profile': 'Profile',
      'editPatient': 'Edit Patient',
      'name': 'Name',
      'phone': 'Phone',
      'medicalHistoryNotes': 'Medical history notes',
      'save': 'Save',
      'notifReminderSarah': 'Reminder: Appointment with Sarah M. at 10:00 AM',
      'notifNewPatientPortal': 'New patient registered from web portal',
      'notifDoctorScheduleUpdated': 'Doctor schedule updated for Dr. Adams',
    },
    'ar': {
      'appName': 'إدارة العيادات الصحية',
      'designedForModernClinics': 'مصمم للعيادات الحديثة',
      'skip': 'تخطي',
      'next': 'التالي',
      'getStarted': 'ابدأ الآن',
      'smartPatientManagement': 'إدارة ذكية للمرضى',
      'smartPatientManagementBody': 'تتبع الملفات والزيارات والتاريخ الطبي بتجربة سهلة على الجوال.',
      'appointmentsThatFlow': 'مواعيد أكثر سلاسة',
      'appointmentsThatFlowBody': 'نظّم الجداول والتنبيهات وحالات المواعيد من لوحة واحدة.',
      'clinicAnalyticsInsights': 'تحليلات العيادة',
      'clinicAnalyticsInsightsBody': 'تابع مؤشرات الأداء والإيرادات لاتخاذ قرارات أدق.',
      'selectLanguageTitle': 'اختر اللغة',
      'selectLanguageSubtitle': 'يرجى اختيار الترجمة المفضلة للمتابعة.',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'continue': 'متابعة',
      'dashboard': 'لوحة التحكم',
      'failedToLoadDashboard': 'فشل تحميل مؤشرات لوحة التحكم',
      'patients': 'المرضى',
      'doctors': 'الأطباء',
      'appointmentsToday': 'مواعيد اليوم',
      'revenue': 'الإيرادات',
      'recentActivity': 'النشاط الأخير',
      'appointmentCompleted': 'تم إنهاء موعد بنجاح',
      'newPatientAdded': 'تمت إضافة ملف مريض جديد',
      'prescriptions': 'الوصفات',
      'appointments': 'المواعيد',
      'unableToLoadAppointments': 'تعذر تحميل المواعيد',
      'appointment': 'موعد',
      'pending': 'قيد الانتظار',
      'noAppointments': 'لا توجد مواعيد',
      'noAppointmentsSubtitle': 'أنشئ أول موعد وابدأ متابعة حالاته بسهولة.',
      'createAppointment': 'إنشاء موعد',
      'calendarView': 'عرض التقويم',
      'calendarViewSubtitle': 'اختر التاريخ والوقت من التقويم المدمج',
      'appointmentStatus': 'حالة الموعد',
      'scheduled': 'مجدول',
      'checkedIn': 'تم تسجيل الحضور',
      'completed': 'مكتمل',
      'cancelled': 'ملغي',
      'saveAppointment': 'حفظ الموعد',
      'unableToLoadDoctors': 'تعذر تحميل الأطباء',
      'specialty': 'التخصص',
      'general': 'عام',
      'scheduleReady': 'الجدول متاح',
      'noDoctors': 'لا يوجد أطباء',
      'noDoctorsSubtitle': 'أضف الأطباء والتخصصات والجداول لتنسيق الرعاية.',
      'noPrescriptionsYet': 'لا توجد وصفات بعد',
      'noPrescriptionsSubtitle': 'واجهة الوصفات جاهزة حتى يتم تفعيل API في الخادم.',
      'medicine': 'الدواء',
      'dose': 'الجرعة',
      'na': 'غير متاح',
      'create': 'إنشاء',
      'notifications': 'الإشعارات',
      'pushReadyReminder': 'تنبيه جاهز للإشعارات الفورية',
      'analytics': 'التحليلات',
      'patientStatistics': 'إحصائيات المرضى',
      'revenueTrend': 'اتجاه الإيرادات',
      'loginTitle': 'تسجيل دخول العيادة',
      'loginSubtitle': 'دخول آمن للأطباء وطاقم العمل',
      'welcomeBack': 'مرحبًا بعودتك',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'login': 'تسجيل الدخول',
      'signingIn': 'جارٍ تسجيل الدخول...',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'createClinicAccount': 'إنشاء حساب عيادة',
      'unlockWithBiometrics': 'فتح بالبصمة',
      'hipaaMinded': 'أمان عالي',
      'medicalFirstUx': 'تجربة طبية أولاً',
      'realtimeWorkflows': 'سير عمل فوري',
      'createClinicAccountTitle': 'إنشاء حساب عيادة',
      'setupClinicWorkspace': 'إعداد مساحة العيادة',
      'setupClinicWorkspaceSubtitle': 'أنشئ تجربة صحية احترافية خلال دقيقتين.',
      'clinicName': 'اسم العيادة',
      'firstName': 'الاسم الأول',
      'lastName': 'اسم العائلة',
      'adminEmail': 'بريد المدير',
      'creating': 'جارٍ الإنشاء...',
      'createPremiumWorkspace': 'إنشاء مساحة احترافية',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟ تسجيل الدخول',
      'forgotPasswordTitle': 'نسيت كلمة المرور',
      'sendResetLink': 'إرسال رابط الاستعادة',
      'sending': 'جارٍ الإرسال...',
      'resetInstructionsSent': 'إذا كان الحساب موجودًا فسيتم إرسال تعليمات الاستعادة.',
      'addPatient': 'إضافة مريض',
      'patient': 'مريض',
      'noPatientsYet': 'لا يوجد مرضى بعد',
      'noPatientsSubtitle': 'أضف أول مريض لبدء متابعة التاريخ والزيارات.',
      'home': 'الرئيسية',
      'profile': 'الملف الشخصي',
      'editPatient': 'تعديل بيانات المريض',
      'name': 'الاسم',
      'phone': 'الهاتف',
      'medicalHistoryNotes': 'ملاحظات التاريخ الطبي',
      'save': 'حفظ',
      'notifReminderSarah': 'تذكير: موعد مع سارة الساعة 10:00 صباحًا',
      'notifNewPatientPortal': 'تم تسجيل مريض جديد من بوابة الويب',
      'notifDoctorScheduleUpdated': 'تم تحديث جدول الدكتور آدامز',
    },
  };

  String tr(String key) {
    final lang = locale.languageCode;
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}

extension AppTranslateExt on BuildContext {
  String tr(String key) => AppLocalizations.of(this).tr(key);
}
